export const daysArray = [
  { value: '1', title: '1 Day' },
  { value: '2', title: '2 Days' },
  { value: '3', title: '3 Days' },
  { value: '4', title: '4 Days' },
  { value: '5', title: '5 Days' },
  { value: '6', title: '6 Days' },
  { value: '7', title: '7 Days' },
  { value: '8', title: '8 Days' },
  { value: '9', title: '9 Days' },
  { value: '10', title: '10 Days' },
  { value: '11', title: '11 Days' },
  { value: '12', title: '12 Days' },
  { value: '13', title: '13 Days' },
  { value: '14', title: '14 Days' },
  { value: '15', title: '15 Days' },
  { value: '16', title: '16 Days' },
  { value: '17', title: '17 Days' },
  { value: '18', title: '18 Days' },
  { value: '19', title: '19 Days' },
  { value: '20', title: '20 Days' },
  { value: '21', title: '21 Days' },
  { value: '22', title: '22 Days' },
  { value: '23', title: '23 Days' },
  { value: '24', title: '24 Days' },
  { value: '25', title: '25 Days' },
  { value: '26', title: '26 Days' },
  { value: '27', title: '27 Days' },
  { value: '28', title: '28 Days' },
  { value: '29', title: '29 Days' },
  { value: '30', title: '30 Days' },
]
export const checkHeadFieldsProfile = [
  'Name',
  'Title',
  'Company',
  'Account Last Activity',
  'Contact Last Activity',
  'Contact Location',
  '# Employees',
  'Keywords',
  'Email',
  'Industry',
  'Contact Stage',
  'Contact Created',
  'Account Stage',
  'Company Country',
  'Company State',
  'Company City',
  'Company Location',
  'Account Created',
  'Contact Lists',
  'Quick Actions',
  'City',
  'State',
  'Country',
  'Account Lists',
  'Contact Engagement',
  'Contact Owner',
  'Account Owner',
  'Parent Account',
  'Account Engagement',
  'ZB SMTP Provider',
  'ZB Status',
  'CRM ID',
  'Phone',
]

export const checkHeadFieldsCompany = [
  'Company',
  'Actions',
  '# Employees',
  'Industry',
  'Keywords',
  'Company Location',
  'Account Owner',
  'Parent Account',
  'Company Summary',
  'Subsidiary of',
  'Account Stage',
  'Account Lists',
  'Account Engagement',
  'Account Last Activity',
  'Account Created',
  'Company City',
  'Company State',
  'Company Country',
]
