export const metadataContact = [
  {
    type: 'single',
    fieldname: 'name',
    section: 'contact',
    xpath: './td[1]/div[1]/div[2]/div/div/div[1]/div/div[1]/div/a',
  },
  {
    type: 'single',
    fieldname: 'id',
    section: 'contact',
    xpath: './td[1]/div[1]/div[2]/div/div/div[1]/div/div[1]/div/a',
  },
  {
    type: 'single',
    fieldname: 'linkedin',
    section: 'contact',
    xpath: './td[1]/div[1]/div[2]/div/div/div[1]/div/div[2]/span/a',
  },
  {
    type: 'single',
    fieldname: 'title',
    section: 'contact',
    xpath: './td[2]/div[1]/div/div/div[1]/span',
  },
  {
    type: 'single',
    fieldname: 'company',
    section: 'contact',
    xpath: './td[3]/div[1]/div/div/div[1]/span/div/div[1]/a',
  },
  {
    type: 'single',
    fieldname: 'company_link',
    section: 'contact',
    xpath: './td[3]/div[1]/div/div/div[1]/span/div/div[2]/span[1]/a',
  },
  {
    type: 'single',
    fieldname: 'company_linkedin',
    section: 'contact',
    xpath: './td[3]/div[1]/div/div/div[1]/span/div/div[2]/span[2]/a',
  },
  {
    type: 'single',
    fieldname: 'company_facebook',
    section: 'contact',
    xpath: './td[3]/div[1]/div/div/div[1]/span/div/div[2]/span[3]/a',
  },
  {
    type: 'single',
    fieldname: 'company_twitter',
    section: 'contact',
    xpath: './td[3]/div[1]/div/div/div[1]/span/div/div[2]/span[4]/a',
  },
  { type: 'single', fieldname: 'account_last_activity', section: 'contact', xpath: './td[4]/span' },
  { type: 'single', fieldname: 'contact_last_activity', section: 'contact', xpath: './td[5]/span' },
  {
    type: 'single',
    fieldname: 'contact_location',
    section: 'contact',
    xpath: './td[6]/div[1]/div/div/div[1]/span',
  },
  { type: 'single', fieldname: '#employees', section: 'contact', xpath: './td[7]/span' },
  { type: 'single', fieldname: 'keywords', section: 'contact', xpath: './td[8]/span/div' },
  {
    type: 'single',
    fieldname: 'email',
    section: 'contact',
    xpath: './td[9]/div[1]/div/div/div[1]/div/div/div/div/div/a',
  },
  {
    type: 'single',
    fieldname: 'status_email',
    section: 'contact',
    xpath: './td[9]/div[1]/div/div/div[1]/div/div/i',
  },
  { type: 'single', fieldname: 'industry', section: 'contact', xpath: './td[10]/span/div' },
  {
    type: 'single',
    fieldname: 'phone',
    section: 'contact',
    xpath: './td[11]/div[1]/div/div/div[1]/span/div/a',
  },
  {
    type: 'single',
    fieldname: 'contact_stage',
    section: 'contact',
    xpath: './td[12]/div[1]/div/div',
  },
  { type: 'single', fieldname: 'contact_created', section: 'contact', xpath: './td[13]/span' },
  {
    type: 'single',
    fieldname: 'account_stage',
    section: 'contact',
    xpath: './td[14]/div[1]/div/div/div[1]/div/div/div/span',
  },
  { type: 'single', fieldname: 'company_country', section: 'contact', xpath: './td[15]/span' },
  { type: 'single', fieldname: 'company_state', section: 'contact', xpath: './td[16]/span' },
  { type: 'single', fieldname: 'company_city', section: 'contact', xpath: './td[17]/span' },
  { type: 'single', fieldname: 'company_location', section: 'contact', xpath: './td[18]/span' },
  { type: 'single', fieldname: 'account_created', section: 'contact', xpath: './td[19]/span' },
  {
    type: 'single',
    fieldname: 'contact_lists',
    section: 'contact',
    xpath: './td[20]/span/div/div/div/span',
  },
  { type: 'single', fieldname: 'city', section: 'contact', xpath: './td[22]/span' },
  { type: 'single', fieldname: 'country', section: 'contact', xpath: './td[23]/span' },
  { type: 'single', fieldname: 'state', section: 'contact', xpath: './td[24]/span' },
]

export const metadataCompany = [
  {
    type: 'single',
    fieldname: 'name',
    section: 'company',
    xpath: './td[1]/div[1]/div[2]/div/div/div[1]/span/div/div[1]/a',
  },
  {
    type: 'single',
    fieldname: 'id',
    section: 'company',
    xpath: './td[1]/div[1]/div[2]/div/div/div[1]/span/div/div[1]/a',
  },
  {
    type: 'single',
    fieldname: 'company_link',
    section: 'company',
    xpath: './td[1]/div[1]/div[2]/div/div/div[1]/span/div/div[2]/span[1]/a',
  },
  {
    type: 'single',
    fieldname: 'company_linkedin',
    section: 'company',
    xpath: './td[1]/div[1]/div[2]/div/div/div[1]/span/div/div[2]/span[2]/a',
  },
  {
    type: 'single',
    fieldname: 'company_facebook',
    section: 'company',
    xpath: './td[1]/div[1]/div[2]/div/div/div[1]/span/div/div[2]/span[3]/a',
  },
  {
    type: 'single',
    fieldname: 'company_twitter',
    section: 'company',
    xpath: './td[1]/div[1]/div[2]/div/div/div[1]/span/div/div[2]/span[4]/a',
  },
  { type: 'single', fieldname: '#employees', section: 'company', xpath: './td[3]/span' },
  { type: 'single', fieldname: 'industry', section: 'company', xpath: './td[4]/span/div/span' },
  { type: 'single', fieldname: 'keywords', section: 'company', xpath: './td[5]/span/div' },
  { type: 'single', fieldname: 'company_location', section: 'company', xpath: './td[6]/span' },
]
