export interface Contact {
  name: string | number
  id: string | number
  linkedin: string | number
  title: string | number
  company: string | number
  company_link: string | number
  company_linkedin: string | number
  company_facebook: string | number
  company_twitter: string | number
  account_last_activity: string | number
  contact_last_activity: string | number
  contact_location: string | number
  '#employees': string | number
  keywords: string | number
  email: string | number
  status_email: string | number
  industry: string | number
  phone: string | number
  contact_stage: string | number
  contact_created: string | number
  account_stage: string | number
  company_country: string | number
  company_state: string | number
  company_city: string | number
  company_location: string | number
  account_created: string | number
  contact_lists: string | number
  city: string | number
  country: string | number
  state: string | number
  apollo_url: string | number
}
